/**
 * Deterministic fixture generator.
 *
 * Writes `fixtures/deposit-batch.json`, which is consumed verbatim by:
 *   - the Vitest suite in this package,
 *   - `minaport-core`'s Rust tests (packages/prover),
 *   - `MinaPortEncoding.t.sol` (packages/flare-contracts).
 *
 * If any of the three implementations drifts, its test fails against this file.
 * Regenerate with `pnpm --filter @minaport/shared fixtures`.
 *
 * Everything here is hard-coded — no randomness, no clock — so the output is
 * byte-stable across machines and can be committed.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  BATCH_DOMAIN,
  DEPOSIT_LEAF_DOMAIN,
  WITHDRAWAL_LEAF_DOMAIN,
} from '../constants.js';
import { encodeDepositLeaf, encodeSettlementPublicValues, hashDepositLeaf, hashWithdrawal } from '../encoding.js';
import { EMPTY_LEAF } from '../merkle.js';
import { allClaimBundles, batchPublicValues, buildDepositBatch } from '../batch.js';
import { encodeMinaRecipient } from '../minaAddress.js';
import type { DepositLeaf } from '../types.js';

const here = dirname(fileURLToPath(import.meta.url));
const outputPath = resolve(here, '../../fixtures/deposit-batch.json');

/** Three distinct Mina senders, chosen as small field elements for readability. */
const SENDERS = [
  { x: '0x0000000000000000000000000000000000000000000000000000000000000001', isOdd: false },
  { x: '0x0000000000000000000000000000000000000000000000000000000000000002', isOdd: true },
  { x: '0x00000000000000000000000000000000000000000000000000000000000000ff', isOdd: false },
] as const;

const RECIPIENTS = [
  '0x1111111111111111111111111111111111111111',
  '0x2222222222222222222222222222222222222222',
  '0x3333333333333333333333333333333333333333',
] as const;

const DEPOSITS: DepositLeaf[] = [
  { nonce: 0n, sender: SENDERS[0], recipientFlare: RECIPIENTS[0], amountNanomina: 1_000_000_000n },
  { nonce: 1n, sender: SENDERS[1], recipientFlare: RECIPIENTS[1], amountNanomina: 2_500_000_000n },
  { nonce: 2n, sender: SENDERS[2], recipientFlare: RECIPIENTS[2], amountNanomina: 1n },
];

const BRIDGE_ID = '0x00000000000000000000000000000000000000000000000000006d696e61706f' as const;
const PREVIOUS_ACTION_STATE =
  '0x0000000000000000000000000000000000000000000000000000000000000000' as const;
const NEW_ACTION_STATE =
  '0x00000000000000000000000000000000000000000000000000000000000000aa' as const;

function main(): void {
  const batch = buildDepositBatch({
    bridgeId: BRIDGE_ID,
    previousActionState: PREVIOUS_ACTION_STATE,
    newActionState: NEW_ACTION_STATE,
    batchNonce: 1n,
    deposits: DEPOSITS,
  });

  const publicValues = batchPublicValues(batch);

  const fixture = {
    _comment:
      'Generated by @minaport/shared. Do not edit by hand — run `pnpm --filter @minaport/shared fixtures`.',
    domains: {
      depositLeaf: DEPOSIT_LEAF_DOMAIN,
      withdrawalLeaf: WITHDRAWAL_LEAF_DOMAIN,
      batch: BATCH_DOMAIN,
      emptyLeaf: EMPTY_LEAF,
    },
    batch: {
      bridgeId: batch.bridgeId,
      previousActionState: batch.previousActionState,
      newActionState: batch.newActionState,
      batchNonce: batch.batchNonce.toString(),
      depositsRoot: batch.depositsRoot,
    },
    deposits: batch.deposits.map((deposit, index) => ({
      nonce: deposit.nonce.toString(),
      senderMinaX: deposit.sender.x,
      senderMinaIsOdd: deposit.sender.isOdd,
      recipientFlare: deposit.recipientFlare,
      amountNanomina: deposit.amountNanomina.toString(),
      preimage: encodeDepositLeaf(deposit),
      leafHash: hashDepositLeaf(deposit),
      merkleProof: allClaimBundles(batch)[index]!.merkleProof,
    })),
    publicValues: {
      decoded: { ...publicValues, batchNonce: publicValues.batchNonce.toString() },
      encoded: encodeSettlementPublicValues(publicValues),
    },
    withdrawal: (() => {
      const record = {
        nonce: 7n,
        sender: '0x4444444444444444444444444444444444444444' as const,
        minaRecipient: encodeMinaRecipient(SENDERS[1]),
        amountNanomina: 500_000_000n,
      };
      return {
        nonce: record.nonce.toString(),
        sender: record.sender,
        minaRecipient: record.minaRecipient,
        amountNanomina: record.amountNanomina.toString(),
        hash: hashWithdrawal(record),
      };
    })(),
  };

  mkdirSync(dirname(outputPath), { recursive: true });
  writeFileSync(outputPath, `${JSON.stringify(fixture, null, 2)}\n`, 'utf8');
  console.log(`wrote ${outputPath}`);
}

main();
